# Generated by Django 4.0.3 on 2022-03-25 12:42

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True, verbose_name='Savol')),
                ('op1', models.CharField(max_length=200, null=True, verbose_name='A javob')),
                ('op2', models.CharField(max_length=200, null=True, verbose_name='B javob')),
                ('op3', models.CharField(max_length=200, null=True, verbose_name='C javob')),
                ('op4', models.CharField(max_length=200, null=True, verbose_name='D javob')),
                ('ans', models.CharField(max_length=200, null=True, verbose_name='Haqiqiy javob')),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(validators=[quiz.models.get_number])),
                ('score', models.FloatField()),
            ],
        ),
    ]
