# Generated by Django 4.0.2 on 2022-02-15 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_profile_phone'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_test', to='topic.lesson'),
        ),
    ]
