# Generated by Django 4.0.2 on 2022-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quesmodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='ans',
            field=models.CharField(max_length=200, null=True, verbose_name='Haqiqiy javob'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op1',
            field=models.CharField(max_length=200, null=True, verbose_name='A javob'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op2',
            field=models.CharField(max_length=200, null=True, verbose_name='B javob'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op3',
            field=models.CharField(max_length=200, null=True, verbose_name='C javob'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op4',
            field=models.CharField(max_length=200, null=True, verbose_name='D javob'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(max_length=200, null=True, verbose_name='Savol'),
        ),
    ]
