# Generated by Django 4.0.2 on 2022-02-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0009_post_photo_alter_post_slug'),
        ('quiz', '0003_alter_quesmodel_ans_alter_quesmodel_op1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_test', to='topic.lesson'),
        ),
    ]
