# Generated by Django 5.0.7 on 2024-09-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_resultmodel_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quesmodel',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='resultmodel',
            options={'verbose_name': 'Natija', 'verbose_name_plural': 'Natijalar'},
        ),
    ]
