# Generated by Django 5.0.7 on 2024-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quesmodel_options_alter_resultmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.TextField(null=True, verbose_name='Savol'),
        ),
    ]
