# Generated by Django 4.0.3 on 2022-03-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0010_alter_lesson_description'),
        ('quiz', '0004_alter_quesmodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic', to='topic.lesson'),
        ),
    ]
