# Generated by Django 4.0.3 on 2022-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_order',
            new_name='order',
        ),
    ]
