# Generated by Django 5.0.7 on 2024-07-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_aboutproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
