# Generated by Django 4.0.5 on 2022-07-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_alter_lesson_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description_photo',
            field=models.ManyToManyField(related_name='photomodels', to='topic.photomodel'),
        ),
    ]
