# Generated by Django 5.0.7 on 2024-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_aboutproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('title', models.CharField(max_length=250)),
                ('link', models.URLField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Useful Link',
                'verbose_name_plural': 'Useful Links',
            },
        ),
    ]
