# Generated by Django 4.0.5 on 2022-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_alter_lesson_description_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description_photo',
            field=models.ManyToManyField(blank=True, related_name='photomodels', to='topic.photomodel'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
