# Generated by Django 5.0.7 on 2024-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_usefullink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
            options={
                'verbose_name': 'Nazorat ishi',
                'verbose_name_plural': 'Nazorat ishlari',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutproject',
            options={'verbose_name': 'Loyiha haqida'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='photomodel',
            options={'verbose_name': 'Dars rasmi', 'verbose_name_plural': 'Dars rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Shaxsiy kabinet', 'verbose_name_plural': 'Shaxsiy kabinetlar'},
        ),
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='usefullink',
            options={'verbose_name': 'Foydali link', 'verbose_name_plural': 'Foydali linklar'},
        ),
    ]
