# Generated by Django 4.0.2 on 2022-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(verbose_name='Maruzasi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Mavzusi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video lavha'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gruh',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Gruh'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='kursi',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Kursi'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='sharifi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sharifi'),
        ),
    ]
