# Generated by Django 5.0.7 on 2024-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_controlwork_alter_aboutproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlwork',
            name='type',
            field=models.CharField(choices=[('jn', 'Joriy Nazorat'), ('on', 'Oraliq Nazorat'), ('yn', 'Yakuniy Nazorat')], default='jn', max_length=20),
        ),
    ]
