# Generated by Django 5.0.7 on 2024-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0007_controlwork_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
            options={
                'verbose_name': 'Glossariy',
                'verbose_name_plural': 'Glossariy',
            },
        ),
    ]
